version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: cruise-rabbitmq
    ports:
      - "5672:5672"       # AMQP protocol
      - "15672:15672"     # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - cruise-network

volumes:
  rabbitmq_data:

networks:
  cruise-network:
    driver: bridge

