APPROVED_PAYMENT_RESERVE_NAME = "approved_payment_reserve"
APPROVED_PAYMENT_TICKET_NAME = "approved_payment_ticket"
APPROVED_PAYMENT_EXCHANGE = "payment.status"
DENIED_PAYMENT_NAME = "denied_payment"
TICKET_GENERATED_NAME = "ticket_generated"
PROMOTION_EXCHANGE_NAME = "promotion_exchange"
PROMOTION_QUEUE_NAME = "promotion_id_"
CREATED_RESERVE_Q_NAME = "created_reserve"
CANCELLED_RESERVE_Q_NAME = "cancelled_reserve"

RABBITMQ_HOST = "localhost"

APPROVED_PAYMENT_ROUTING_KEY = "payment.OK"
PROMOTIONS_ROUTING_KEY = "promotions_id_"

MAIN_PORT = 5050
ITINERARIES_PORT = 5001
PAYMENT_PORT = 5002
PAYMENT_INTERNAL_PORT = 5003
RESERVER_PORT = 5004